from __future__ import annotations

import argparse
import json
import logging
from collections import defaultdict
from pathlib import Path

import pandas as pd
from sklearn.model_selection import StratifiedGroupKFold

LOGGER = logging.getLogger(__name__)


class UnionFind:
    """Disjoint-set structure for building duplicate and similarity groups."""

    def __init__(self, items: list[str]) -> None:
        self.parent = {item: item for item in items}
        self.rank = {item: 0 for item in items}

    def find(self, item: str) -> str:
        if self.parent[item] != item:
            self.parent[item] = self.find(self.parent[item])
        return self.parent[item]

    def union(self, first: str, second: str) -> None:
        root_first = self.find(first)
        root_second = self.find(second)

        if root_first == root_second:
            return

        if self.rank[root_first] < self.rank[root_second]:
            self.parent[root_first] = root_second
        elif self.rank[root_first] > self.rank[root_second]:
            self.parent[root_second] = root_first
        else:
            self.parent[root_second] = root_first
            self.rank[root_first] += 1


def load_near_duplicates(path: Path) -> list[dict]:
    """Load perceptually similar image pairs generated by the audit script."""
    if not path.exists():
        LOGGER.warning("Near-duplicate file not found: %s", path)
        return []

    with path.open("r", encoding="utf-8") as file:
        payload = json.load(file)

    if not isinstance(payload, list):
        raise ValueError("near_duplicates.json must contain a JSON list.")

    return payload


def remove_duplicate_images(
    inventory: pd.DataFrame,
    near_duplicates: list[dict],
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Remove redundant images.

    Images are considered redundant when:
    - they have the same SHA-256 value, or
    - their perceptual hash distance is zero.

    One canonical image is retained from every duplicate component.
    """
    paths = inventory["path"].tolist()
    known_paths = set(paths)
    duplicate_uf = UnionFind(paths)

    # Exact byte-level duplicates.
    for _, group in inventory.groupby("sha256"):
        group_paths = sorted(group["path"].tolist())
        for path in group_paths[1:]:
            duplicate_uf.union(group_paths[0], path)

    # Visually identical images whose files differ.
    for pair in near_duplicates:
        first = pair["file_1"]
        second = pair["file_2"]
        distance = int(pair["phash_distance"])

        if first not in known_paths or second not in known_paths:
            continue

        if distance == 0:
            duplicate_uf.union(first, second)

    components: dict[str, list[str]] = defaultdict(list)
    for path in paths:
        components[duplicate_uf.find(path)].append(path)

    retained_paths: set[str] = set()
    removed_rows: list[dict] = []

    for component_paths in components.values():
        ordered_paths = sorted(component_paths)
        canonical = ordered_paths[0]
        retained_paths.add(canonical)

        for removed_path in ordered_paths[1:]:
            removed_rows.append(
                {
                    "removed_path": removed_path,
                    "retained_path": canonical,
                    "reason": "exact_or_phash_zero_duplicate",
                }
            )

    cleaned = inventory[inventory["path"].isin(retained_paths)].copy()
    cleaned = cleaned.sort_values("path").reset_index(drop=True)

    removed = pd.DataFrame(
        removed_rows,
        columns=["removed_path", "retained_path", "reason"],
    )

    return cleaned, removed


def assign_similarity_groups(
    inventory: pd.DataFrame,
    near_duplicates: list[dict],
    maximum_distance: int,
) -> pd.DataFrame:
    """
    Assign visually similar images to the same group.

    These groups are later kept entirely within one dataset split, preventing
    visually similar images from appearing in both training and evaluation.
    """
    paths = inventory["path"].tolist()
    retained_paths = set(paths)
    similarity_uf = UnionFind(paths)

    for pair in near_duplicates:
        first = pair["file_1"]
        second = pair["file_2"]
        distance = int(pair["phash_distance"])

        if distance > maximum_distance:
            continue

        # A duplicate may already have been removed, so only group retained files.
        if first not in retained_paths or second not in retained_paths:
            continue

        similarity_uf.union(first, second)

    roots = [similarity_uf.find(path) for path in paths]
    unique_roots = {
        root: index
        for index, root in enumerate(sorted(set(roots)))
    }

    result = inventory.copy()
    result["group_id"] = [
        f"group_{unique_roots[root]:04d}"
        for root in roots
    ]

    # A similarity group must never contain contradictory labels.
    labels_per_group = result.groupby("group_id")["label"].nunique()
    invalid_groups = labels_per_group[labels_per_group > 1]

    if not invalid_groups.empty:
        details = result[
            result["group_id"].isin(invalid_groups.index)
        ][["path", "label", "group_id"]]

        raise ValueError(
            "Some near-duplicate groups contain multiple class labels:\n"
            f"{details.to_string(index=False)}"
        )

    return result


def choose_best_grouped_fold(
    dataframe: pd.DataFrame,
    number_of_splits: int,
    seed: int,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Select the grouped stratified fold closest to the full class distribution.

    Returns:
        remaining_data, held_out_data
    """
    splitter = StratifiedGroupKFold(
        n_splits=number_of_splits,
        shuffle=True,
        random_state=seed,
    )

    overall_distribution = (
        dataframe["label"]
        .value_counts(normalize=True)
        .sort_index()
    )

    best_score: float | None = None
    best_indices: tuple[list[int], list[int]] | None = None

    features = dataframe[["path"]]
    labels = dataframe["label"]
    groups = dataframe["group_id"]

    for remaining_indices, held_out_indices in splitter.split(
        features,
        labels,
        groups,
    ):
        held_out = dataframe.iloc[held_out_indices]

        held_out_distribution = (
            held_out["label"]
            .value_counts(normalize=True)
            .reindex(overall_distribution.index, fill_value=0.0)
        )

        expected_fraction = 1.0 / number_of_splits
        actual_fraction = len(held_out) / len(dataframe)

        size_error = abs(actual_fraction - expected_fraction)
        distribution_error = (
            held_out_distribution - overall_distribution
        ).abs().sum()

        score = size_error + distribution_error

        if best_score is None or score < best_score:
            best_score = score
            best_indices = (
                remaining_indices.tolist(),
                held_out_indices.tolist(),
            )

    if best_indices is None:
        raise RuntimeError("Could not generate a grouped stratified split.")

    remaining_indices, held_out_indices = best_indices

    remaining = dataframe.iloc[remaining_indices].copy()
    held_out = dataframe.iloc[held_out_indices].copy()

    return remaining, held_out


def validate_splits(
    train: pd.DataFrame,
    validation: pd.DataFrame,
    test: pd.DataFrame,
) -> None:
    """Verify that paths and similarity groups do not leak across splits."""
    splits = {
        "train": train,
        "validation": validation,
        "test": test,
    }

    names = list(splits)

    for index, first_name in enumerate(names):
        first = splits[first_name]

        if first["path"].duplicated().any():
            raise ValueError(f"Duplicate paths inside {first_name} split.")

        for second_name in names[index + 1:]:
            second = splits[second_name]

            shared_paths = set(first["path"]) & set(second["path"])
            if shared_paths:
                raise ValueError(
                    f"Path leakage between {first_name} and {second_name}: "
                    f"{sorted(shared_paths)}"
                )

            shared_groups = set(first["group_id"]) & set(second["group_id"])
            if shared_groups:
                raise ValueError(
                    f"Similarity-group leakage between {first_name} "
                    f"and {second_name}: {sorted(shared_groups)}"
                )


def class_counts(dataframe: pd.DataFrame) -> dict[str, int]:
    """Return class counts as regular JSON-compatible integers."""
    return {
        label: int(count)
        for label, count in dataframe["label"].value_counts().sort_index().items()
    }


def create_splits(
    inventory_path: Path,
    near_duplicates_path: Path,
    output_dir: Path,
    maximum_phash_distance: int,
    seed: int,
) -> None:
    """Create duplicate-safe train, validation, and test CSV files."""
    output_dir.mkdir(parents=True, exist_ok=True)

    inventory = pd.read_csv(inventory_path)

    required_columns = {"path", "label", "sha256", "phash"}
    missing_columns = required_columns - set(inventory.columns)

    if missing_columns:
        raise ValueError(
            f"Inventory is missing required columns: {sorted(missing_columns)}"
        )

    near_duplicates = load_near_duplicates(near_duplicates_path)

    cleaned, removed = remove_duplicate_images(
        inventory=inventory,
        near_duplicates=near_duplicates,
    )

    grouped = assign_similarity_groups(
        inventory=cleaned,
        near_duplicates=near_duplicates,
        maximum_distance=maximum_phash_distance,
    )

    # Approximately 1/7 = 14.3% of the complete dataset becomes the test set.
    train_validation, test = choose_best_grouped_fold(
        dataframe=grouped,
        number_of_splits=7,
        seed=seed,
    )

    # Approximately 1/6 of the remaining 85.7% = 14.3% overall.
    train, validation = choose_best_grouped_fold(
        dataframe=train_validation,
        number_of_splits=6,
        seed=seed + 1,
    )

    train = train.sort_values("path").reset_index(drop=True)
    validation = validation.sort_values("path").reset_index(drop=True)
    test = test.sort_values("path").reset_index(drop=True)

    validate_splits(train, validation, test)

    output_columns = ["path", "label", "group_id"]

    train[output_columns].to_csv(output_dir / "train.csv", index=False)
    validation[output_columns].to_csv(
        output_dir / "validation.csv",
        index=False,
    )
    test[output_columns].to_csv(output_dir / "test.csv", index=False)
    removed.to_csv(output_dir / "removed_duplicates.csv", index=False)

    total = len(grouped)

    summary = {
        "seed": seed,
        "maximum_phash_distance": maximum_phash_distance,
        "images_before_deduplication": int(len(inventory)),
        "images_after_deduplication": int(len(grouped)),
        "removed_duplicate_images": int(len(removed)),
        "splits": {
            "train": {
                "count": int(len(train)),
                "fraction": round(len(train) / total, 4),
                "class_counts": class_counts(train),
            },
            "validation": {
                "count": int(len(validation)),
                "fraction": round(len(validation) / total, 4),
                "class_counts": class_counts(validation),
            },
            "test": {
                "count": int(len(test)),
                "fraction": round(len(test) / total, 4),
                "class_counts": class_counts(test),
            },
        },
    }

    with (output_dir / "split_summary.json").open(
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(summary, file, indent=2)

    LOGGER.info("Created data splits in %s", output_dir.resolve())
    print(json.dumps(summary, indent=2))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create duplicate-safe, stratified dataset splits from an "
            "image inventory."
        )
    )
    parser.add_argument(
        "--inventory",
        type=Path,
        default=Path("reports/dataset_audit/image_inventory.csv"),
        help="CSV inventory produced by audit_dataset.py.",
    )
    parser.add_argument(
        "--near-duplicates",
        type=Path,
        default=Path("reports/dataset_audit/near_duplicates.json"),
        help="Near-duplicate JSON produced by audit_dataset.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("data/splits"),
        help="Directory in which split CSV files will be written.",
    )
    parser.add_argument(
        "--maximum-phash-distance",
        type=int,
        default=2,
        help=(
            "Maximum perceptual-hash distance for images that must remain "
            "within the same split."
        ),
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed used for reproducible splitting.",
    )

    return parser.parse_args()


def main() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(levelname)s: %(message)s",
    )

    args = parse_args()

    create_splits(
        inventory_path=args.inventory,
        near_duplicates_path=args.near_duplicates,
        output_dir=args.output,
        maximum_phash_distance=args.maximum_phash_distance,
        seed=args.seed,
    )


if __name__ == "__main__":
    main()